name: Deploy to Network Solutions
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Sync files over SFTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy via SFTP
        uses: milanmk/actions-file-deployer@master
        with:
          remote-protocol: sftp
          remote-host: ${{ secrets.SFTP_SERVER }}
          remote-port: ${{ secrets.SFTP_PORT }}
          remote-user: ${{ secrets.SFTP_USERNAME }}
          remote-password: ${{ secrets.SFTP_PASSWORD }}
          local-path: './'
          remote-path: './'
          sync: full
          ssh-options: -o HostKeyAlgorithms=+ssh-rsa
